import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { Comments } from "@/components/comments";
import { ApiArticle, publicApi } from "@/lib/api";

const site = process.env.NEXT_PUBLIC_SITE_URL || "https://sutradhaarnews.vercel.app";
async function article(id: string) { return publicApi<ApiArticle>(`/articles/public/${encodeURIComponent(id)}`).catch(() => null); }
export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> { const item = await article((await params).id); if (!item) return {}; const url = `${site}/news/${item.slug}`; return { title: item.seoTitle || item.title, description: item.seoDescription || item.excerpt, alternates: { canonical: item.canonicalUrl || url }, openGraph: { type: "article", title: item.seoTitle || item.title, description: item.seoDescription || item.excerpt || undefined, url, images: item.featuredImage?.deliveryUrl ? [{ url: item.featuredImage.deliveryUrl }] : [] }, twitter: { card: "summary_large_image", title: item.seoTitle || item.title, description: item.seoDescription || item.excerpt || undefined } }; }
export default async function ArticlePage({ params }: { params: Promise<{ id: string }> }) { const item = await article((await params).id); if (!item) notFound(); const related = await publicApi<ApiArticle[]>(`/articles/public/related/${item.slug}`).catch(() => []); const text = typeof item.content === "object" ? item.content?.text : item.content; const url = `${site}/news/${item.slug}`; const jsonLd = { "@context": "https://schema.org", "@type": "NewsArticle", headline: item.title, description: item.excerpt, datePublished: item.publishedAt, dateModified: item.publishedAt, mainEntityOfPage: url, author: { "@type": "Person", name: item.author.name }, publisher: { "@type": "Organization", name: "सूत्रधार न्यूज", logo: { "@type": "ImageObject", url: `${site}/logo.png` } }, image: item.featuredImage?.deliveryUrl ? [item.featuredImage.deliveryUrl] : undefined }; return <><Header /><main><article className="article container"><div className="breadcrumbs"><Link href="/">गृहपृष्ठ</Link><span>/</span><Link href={`/category/${item.category.slug}`}>{item.category.name}</Link></div><span className="article-category">{item.category.name}</span><h1>{item.title}</h1>{item.excerpt && <p className="article-deck">{item.excerpt}</p>}<div className="article-meta"><div className="author-avatar">सू</div><div><strong>{item.author.name}</strong><span>{item.publishedAt ? new Date(item.publishedAt).toLocaleString("ne-NP") : ""}</span></div></div>{item.featuredImage?.deliveryUrl && <><img className="article-hero" src={item.featuredImage.deliveryUrl} alt={item.title} /><small className="caption">{item.featuredImage.title || "तस्बिर: सूत्रधार न्यूज"}</small></>}<div className="article-layout"><div className="article-body">{text ? text.split("\n").filter(Boolean).map((paragraph, index) => <p key={index}>{paragraph}</p>) : <p>यस समाचारको विस्तृत सामग्री उपलब्ध छैन।</p>}</div></div>{item.tags?.length ? <div className="tags"><b>सम्बन्धित विषय:</b>{item.tags.map((tag: { id: string; name: string; slug: string }) => <Link href={`/search?q=${encodeURIComponent(tag.name)}`} key={tag.id}>{tag.name}</Link>)}</div> : null}<section className="related"><div className="section-heading"><h2>सम्बन्धित समाचार</h2></div><div className="related-grid">{related.map((story) => <article key={story.id}><Link href={`/news/${story.slug}`}>{story.featuredImage?.deliveryUrl && <img src={story.featuredImage.deliveryUrl} alt={story.title} />}<span>{story.category.name}</span><h3>{story.title}</h3></Link></article>)}</div></section>{item.allowComments && <Comments articleId={item.id} />}</article></main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Footer /></>; }
